### PR TITLE
Alerting Police Stations using Notifications and Image of an Intruder

### LINKED ISSUE #11: Thief Detection : Alerting Police Stations using Notifications and Image of an Intruder
### Description

Welcome to 'Thief -Detection', good to see you here.

With this issue, the readers will get to know on how to alert police stations using notifications and image of an intruder

It's an interlinked issue with earlier issue of Thief Detection and House Owner Alerts. Discuss with the collaborator assigned to issue number - 6 and 7 and work accordingly

To get assigned to this issue, add your participant id mentioned in this [spreadsheet](https://docs.google.com/spreadsheets/d/1SX9FubA-n1ag_0n4WmzMXd6rq5lrkFmaAWl8fhHvTWM/edit#gid=0) and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot is must to approve 

This issue is only for 'SWOC' contributors

### Domain

Data Science

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/neha07kumari/Thief_Detection/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/neha07kumari/Thief_Detection/blob/main/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by hassanrahim26**
## Related issue

* Info about the related issue.

- [x] I'm an SWOC Participant
- [x] Contributor

Fixes #11 
## Describe the changes you've made

This will send an alert to the police station in form of notification and also with the image of the intruder via telegram bot
For this, You need to generate telegram API key for your police station bot where they will get notifications on intruder and it's image too.

Replace the Telegram Key with your and then run it, You will get a security alert and an image of intruder too, This is done by using Notifly

## Screenshot
intruder

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ]  Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by hassanrahim26** [comment]
@prathimacode-hub, please review my PR.

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub, please review my PR.

Yes, add a screenshot too here of the outcome @HassanRahim26

**Comment by hassanrahim26** [comment]
> > @prathimacode-hub, please review my PR.
> 
> Yes, add a screenshot too here of the outcome @HassanRahim26

@prathimacode-hub, I've added the screenshot.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Amazing work. Keep it up. Get going. Welcome to the repo. 🎉👏@HassanRahim26

**Pull request merged**
